export const items = [
  {
    id: 1,
    category: 'mobiles',
    title: "Apple iPhone 14",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'Apple iPhone 14 (128 GB) - Blue',
    price: '89999',
  },
  {
    id: 2,
    category: 'laptops',
    title: "Xiaomi Notebookpro",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3EzeQaC',
    description: 'Xiaomi Notebookpro with Intel i7 processor',
    price: '49999',
  },
  {
    id: 3,
    category: 'tablets',
    title: "Xiaomi Pad 6",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3ZeNRdY',
    description: 'Xiaomi Pad 6 with Qualcomm Snapdragon 870',
    price: '29999',
  },
  {
    id: 4,
    category: 'mobiles',
    title: "Apple iPhone 11",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/44MiYi6',
    description: 'Apple iPhone 11 (64GB) - White',
    price: '79999',
  },
  {
    id: 5,
    category: 'tablets',
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3RabsdH',
    description: 'Lenovo Tab P12 Pro AMOLED with 8GB RAM, 256GB Storage',
    price: '19999',
  },
  {
    id: 6,
    category: 'mobiles',
    title: "Apple iPhone 13",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3r6XJtv',
    description: 'Apple iPhone 13 (128GB) - Blue',
    price: '69999',
  },
  {
    id: 7,
    category: 'laptops',
    title: "Lenovo IdeaPad Slim 5",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/44JsK4r',
    description: 'Lenovo IdeaPad Slim 5 with Intel Core i5 processor',
    price: '29999',
  },
  {
    id: 8,
    category: 'tablets',
    title: "Samsung Galaxy Tab A8",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3Pdsh4F',
    description: 'Samsung Galaxy Tab A8, 10.5 inch display, 64GB storage',
    price: '49999',
  },
  {
    id: 9,
    category: 'laptops',
    title: "Apple MacBook Air M1",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3r9rvhm',
    description: 'Apple MacBook Air with M1 chip, 13.3-inch Retina display',
    price: '89999',
  },
  {
    id: 10,
    category: 'mobiles',
    title: "Samsung Galaxy S22",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3S2fjAz',
    description: 'Samsung Galaxy S22 with 128GB storage and 8GB RAM',
    price: '79999',
  },
  {
    id: 11,
    category: 'laptops',
    title: "Dell Inspiron 15",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3KnbvJx',
    description: 'Dell Inspiron 15 with Intel i7 processor and 512GB SSD',
    price: '57999',
  },
  {
    id: 12,
    category: 'mobiles',
    title: "Google Pixel 7",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3KbcJvY',
    description: 'Google Pixel 7 with 128GB storage, white color',
    price: '49999',
  },
  {
    id: 13,
    category: 'tablets',
    title: "iPad Air 2022",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3Edf5jK',
    description: 'iPad Air 2022 with M1 chip, 64GB storage, 10.9-inch display',
    price: '45999',
  },
  {
    id: 14,
    category: 'mobiles',
    title: "OnePlus 10 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3zTsRLg',
    description: 'OnePlus 10 Pro with 12GB RAM, 256GB storage',
    price: '64999',
  },
  {
    id: 15,
    category: 'tablets',
    title: "Realme Pad X",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3dfGhlY',
    description: 'Realme Pad X with 10.95 inch display and 128GB storage',
    price: '22999',
  },
  {
    id: 16,
    category: 'mobiles',
    title: "Vivo X70 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3S2Y7XL',
    description: 'Vivo X70 Pro with 12GB RAM and 256GB storage',
    price: '47999',
  },
  {
    id: 17,
    category: 'laptops',
    title: "Acer Predator Helios 300",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3A3MgfG',
    description: 'Acer Predator Helios 300 with Intel i7 and Nvidia RTX 3060',
    price: '89999',
  },
  {
    id: 18,
    category: 'tablets',
    title: "Microsoft Surface Pro 7",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3EdvslF',
    description: 'Microsoft Surface Pro 7 with Intel i5, 8GB RAM, 256GB SSD',
    price: '79999',
  },
  {
    id: 19,
    category: 'mobiles',
    title: "Oppo Reno 7",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3CdVqkI',
    description: 'Oppo Reno 7 with 8GB RAM and 128GB storage',
    price: '31999',
  },
  {
    id: 20,
    category: 'laptops',
    title: "HP Envy 13",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3Kh7t6G',
    description: 'HP Envy 13 with Intel i5 and 16GB RAM',
    price: '69999',
  },

  // Continue this pattern for all 100 items
  // Following items are hypothetical and are designed in the same format

  {
    id: 21,
    category: 'mobiles',
    title: "Realme GT Neo 3",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3fXvScH',
    description: 'Realme GT Neo 3 with 12GB RAM, 256GB storage',
    price: '34999',
  },
  {
    id: 22,
    category: 'tablets',
    title: "Samsung Galaxy Tab S8 Ultra",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3CaHvWT',
    description: 'Samsung Galaxy Tab S8 Ultra with 512GB storage',
    price: '79999',
  },
  {
    id: 23,
    category: 'mobiles',
    title: "OnePlus Nord 2",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3CpJb5F',
    description: 'OnePlus Nord 2 with 8GB RAM, 128GB storage',
    price: '29999',
  },
];
